
export type LightingStyle = 'Natural Light' | 'Studio Light' | 'Golden Hour' | 'Blue Hour' | 'Cinematic' | 'Dramatic';
export type CameraPerspective = 'Front View' | 'Top View' | 'Side View' | '45° Angle' | 'Close-up' | 'Macro Shot';
export type AspectRatio = '1:1' | '16:9' | '9:16' | '4:3' | '3:4';

export interface CustomizationOptions {
  lightingStyle: LightingStyle;
  cameraPerspective: CameraPerspective;
}

export interface ImageFile {
  base64: string;
  mimeType: string;
  name: string;
}

export interface HistoryItem {
  image: ImageFile;
  prompt: string;
}

export interface ProjectBase {
  id: string;
  name: string;
}

export interface CreatorStudioProject extends ProjectBase {
  productImages: ImageFile[];
  styleImages: ImageFile[];
  generatedImage: ImageFile | null;
  history: HistoryItem[];
  options: CustomizationOptions;
  prompt: string;
  isPromptAutoGenerated: boolean;
  styleDescription: string | null;
  isAnalyzingStyle: boolean;
  isLoading: boolean;
  error: string | null;
  uploadingTarget: 'product' | 'style' | null;
  translatedPrompt: string | null;
  isTranslating: boolean;
  editPrompt: string;
  isEditing: boolean;
}


// --- App View ---
export type AppView = 'creator_studio' | 'photoshoot_director' | 'prompt_studio' | 'voice_over_studio' | 'controller_studio' | 'campaign_studio' | 'video_studio' | 'plan_studio' | 'edit_studio';


// --- Photoshoot Director ---
export type ShotType = string;

export interface PhotoshootResult {
  shotType: ShotType;
  image: ImageFile | null;
  isLoading: boolean;
  error: string | null;
  editPrompt: string;
  isEditing: boolean;
}

export interface PhotoshootState {
  productImages: ImageFile[];
  selectedShotTypes: ShotType[];
  results: PhotoshootResult[];
  isGenerating: boolean;
  error: string | null;
  isUploading: boolean;
  customStylePrompt: string;
}

export interface PhotoshootDirectorProject extends ProjectBase, PhotoshootState {}


// --- Prompt Studio ---
export interface PromptStudioHistoryItem {
  image: ImageFile;
  instructions: string;
  generatedPrompt: string;
}

export interface PromptStudioState {
  images: ImageFile[];
  instructions: string;
  generatedPrompt: string | null;
  history: PromptStudioHistoryItem[];
  isLoading: boolean;
  isUploading: boolean;
  error: string | null;
}

export interface PromptStudioProject extends ProjectBase, PromptStudioState {}

// --- Voice Over Studio ---
export interface AudioFile {
  base64: string;
  name: string;
}

export interface VoiceOverHistoryItem {
  audio: AudioFile;
  text: string;
  voice: string;
  style: string;
}

export interface VoiceOverStudioState {
  text: string;
  styleInstructions: string;
  selectedVoice: string;
  generatedAudio: AudioFile | null;
  isLoading: boolean;
  error: string | null;
  history: VoiceOverHistoryItem[];
  isPlaying: boolean;
  voiceGenderFilter: 'All' | 'Male' | 'Female';
  previewLoadingVoice: string | null;
  previewPlayingVoice: string | null;
}

export interface VoiceOverStudioProject extends ProjectBase, VoiceOverStudioState {}

// --- Branding Studio ---
export type BrandingResultCategory = 'Logo Construction Grid' | 'Typography Showcase' | 'Logo Color Variations' | 'Monochrome Version' |
    '3D Glass Logo' | 'Business Card Mockup' | '3D Glass App Icon' | 'Creative Pen Mockup' |
    'Merchandise (Tote Bag)' | 'Pencil Sketch Logo' | 'Notebook Mockup' | 'Waving Flag Mockup';

export interface BrandingResult {
  category: BrandingResultCategory;
  image: ImageFile | null;
  isLoading: boolean;
  isEditing: boolean;
  error: string | null;
  editPrompt: string;
}

export interface BrandingStudioState {
  logos: ImageFile[];
  isUploading: boolean;
  error: string | null;
  results: BrandingResult[];
  colors: string[];
  isAnalyzing: boolean;
  isGenerating: boolean;
  aspectRatio: AspectRatio;
}

export interface BrandingStudioProject extends ProjectBase, BrandingStudioState {}

// --- Controller Studio ---
export type ControlCategory = 'Face' | 'Head' | 'Body' | 'Retouch';

export interface ControllerSlider {
  id: string;
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  category: ControlCategory;
}

export interface ControllerStudioState {
    sourceImages: ImageFile[];
    generatedImage: ImageFile | null;
    isUploading: boolean;
    isGenerating: boolean;
    error: string | null;
    sliders: ControllerSlider[];
    activeCategory: ControlCategory;
    history: HistoryItem[];
}

export interface ControllerStudioProject extends ProjectBase, ControllerStudioState {}

// --- Campaign Studio ---
export type CampaignScenario = string;

export interface CampaignResult {
    scenario: CampaignScenario;
    image: ImageFile | null;
    isLoading: boolean;
    error: string | null;
    editPrompt: string;
    isEditing: boolean;
}

export interface CampaignStudioState {
    productImages: ImageFile[];
    isUploading: boolean;
    isAnalyzing: boolean;
    isGenerating: boolean;
    error: string | null;
    results: CampaignResult[];
    productAnalysis: string | null;
    selectedMood: string;
    customPrompt: string;
    mode: 'auto' | 'custom';
    customIdeas: string[];
}

export interface CampaignStudioProject extends ProjectBase, CampaignStudioState {}

// --- Plan Studio ---
export interface PlanIdea {
    id: string;
    scenario: string;
    caption: string;
    tov: string;
    schedule: string;
    image: ImageFile | null;
    isLoadingImage: boolean;
    imageError: string | null;
}

export interface PlanStudioState {
    productImages: ImageFile[];
    logos: ImageFile[];
    prompt: string;
    targetMarket: string;
    dialect: string;
    categoryAnalysis: string | null;
    isAnalyzingCategory: boolean;
    ideas: PlanIdea[];
    isGeneratingPlan: boolean;
    isUploading: boolean;
    error: string | null;
}

export interface PlanStudioProject extends ProjectBase, PlanStudioState {}

// --- Edit Studio (PRO UPDATED) ---
export interface LocalText {
    id: string; 
    content: string;
    fontSize: number;
    color: string;
    fontFamily: string;
    fontWeight: string;
    x: number;
    y: number;
    isVisible: boolean;
    rotation: number;
    letterSpacing: number;
    lineHeight: number;
    maxWidth: number; // New: Controls wrapping/lines (Percentage of container width)
}

export interface GlobalLayer {
    id: string;
    file: ImageFile;
    scale: number;
    x: number;
    y: number;
}

export interface EditAdjustments {
    sharpness: number;
    lut: string; 
}

export interface EditStudioState {
    baseImages: (ImageFile | null)[];
    localTexts: { [index: number]: LocalText[] }; 
    committedTexts: { [index: number]: LocalText[] }; 
    globalLayers: GlobalLayer[]; 
    adjustments: EditAdjustments;
    isUploading: boolean;
    error: string | null;
}

export interface EditStudioProject extends ProjectBase, EditStudioState {}
