
import React, { useEffect, useRef, useCallback, useState } from 'react';
import { CreatorStudioProject, ImageFile } from '../types';
import { translateText, generateImage, editImage } from '../services/geminiService';
import { resizeImage } from '../utils';
import { ADVERTISING_STYLES, StylePreset } from '../constants';
import CustomizationPanel from './CustomizationPanel';
import ImageWorkspace from './ImageWorkspace';
import PromptEditor from './PromptEditor';
import HistoryPanel from './HistoryPanel';
import ResultDisplay from './ResultDisplay';

interface CreatorStudioProps {
  project: CreatorStudioProject;
  setProject: React.Dispatch<React.SetStateAction<CreatorStudioProject>>;
}

const CreatorStudio: React.FC<CreatorStudioProps> = ({ project, setProject }) => {
  const [selectedStyleId, setSelectedStyleId] = useState<string | null>(null);

  const updateActiveProjectState = useCallback((updater: (projectDraft: CreatorStudioProject) => void) => {
    setProject(currentProject => {
      const projectToUpdate = { ...currentProject };
      updater(projectToUpdate);
      return projectToUpdate;
    });
  }, [setProject]);

  const handleFileUpload = async (files: File[]) => {
    if (!files || files.length === 0) return;
    updateActiveProjectState(p => { p.uploadingTarget = 'product'; p.error = null; });
    try {
      const uploaded = await Promise.all(files.map(async file => {
        const resizedFile = await resizeImage(file, 2048, 2048);
        const reader = new FileReader();
        return new Promise<ImageFile>(res => {
          reader.onloadend = () => res({ base64: (reader.result as string).split(',')[1], mimeType: resizedFile.type, name: resizedFile.name });
          reader.readAsDataURL(resizedFile);
        });
      }));
      updateActiveProjectState(p => { p.productImages = [...p.productImages, ...uploaded]; p.uploadingTarget = null; });
    } catch {
      updateActiveProjectState(p => { p.error = 'فشل رفع الصور. يرجى المحاولة مرة أخرى.'; p.uploadingTarget = null; });
    }
  };

  const selectStylePreset = (style: StylePreset) => {
    setSelectedStyleId(style.id);
    updateActiveProjectState(p => {
      p.styleDescription = style.prompt;
      if (!p.prompt || p.isPromptAutoGenerated) p.prompt = style.prompt;
      else p.prompt = `${p.prompt}. Visual Style: ${style.prompt}`;
    });
  };

  const handleGenerate = useCallback(async () => {
    if (!project || !project.prompt) {
      updateActiveProjectState(p => { p.error = 'يرجى كتابة وصف أو اختيار نمط للبدء.'; });
      return;
    }
    if (project.productImages.length > 3) {
      updateActiveProjectState(p => { p.error = 'يمكن استخدام 3 صور منتج كحد أقصى في التوليد.'; });
      return;
    }
    updateActiveProjectState(p => { p.isLoading = true; p.error = null; p.generatedImage = null; });
    try {
      const result = await generateImage(project.productImages, project.prompt, null);
      updateActiveProjectState(p => {
        p.generatedImage = result;
        p.history = [{ image: result, prompt: project.prompt }, ...p.history];
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err || 'Unknown error');
      console.error('Image generation failed:', err);
      updateActiveProjectState(p => { p.error = `فشل التوليد: ${message}`; });
    } finally {
      updateActiveProjectState(p => { p.isLoading = false; });
    }
  }, [project, updateActiveProjectState]);

  const handleEdit = async (editPromptText: string) => {
    if (!project.generatedImage) return;
    updateActiveProjectState(p => { p.isEditing = true; p.error = null; });
    try {
      const result = await editImage(project.generatedImage, editPromptText);
      updateActiveProjectState(p => {
        p.generatedImage = result;
        p.history = [{ image: result, prompt: editPromptText }, ...p.history];
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err || 'Unknown error');
      console.error('Image edit failed:', err);
      updateActiveProjectState(p => { p.error = `فشل التعديل: ${message}`; });
    } finally {
      updateActiveProjectState(p => { p.isEditing = false; });
    }
  };

  return (
    <main className="w-full grid grid-cols-1 lg:grid-cols-2 gap-8 pt-4 pb-12 items-start text-right">
      <div className="flex flex-col gap-6 order-1">
        <div className="glass-card p-6 rounded-3xl border border-white/5 shadow-xl bg-gradient-to-br from-white/5 to-transparent">
          <h3 className="text-xs font-black text-[var(--color-accent)] uppercase tracking-[0.2em] mb-4">1. ارفع صورة منتجك</h3>
          <ImageWorkspace id="creator-product-uploader" title="ارفع المنتج هنا" images={project.productImages} onImagesUpload={handleFileUpload} onImageRemove={(idx) => updateActiveProjectState(p => { p.productImages = p.productImages.filter((_, i) => i !== idx); })} onImageUpdate={(idx, img) => updateActiveProjectState(p => { p.productImages[idx] = img; })} isUploading={project.uploadingTarget === 'product'} />
        </div>
        <div className="glass-card p-6 rounded-3xl border border-white/5 shadow-xl bg-gradient-to-br from-white/5 to-transparent">
          <h3 className="text-xs font-black text-[var(--color-accent)] uppercase tracking-[0.2em] mb-4">2. اختر نمطاً إعلانياً مقترحاً</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {ADVERTISING_STYLES.map((style) => (
              <button key={style.id} onClick={() => selectStylePreset(style)} className={`flex flex-col items-center justify-center gap-2 p-3 rounded-2xl border-2 transition-all group ${selectedStyleId === style.id ? 'border-[var(--color-accent)] bg-[var(--color-accent)]/10 scale-105 shadow-lg shadow-[var(--color-accent)]/20' : 'border-white/5 bg-black/20 hover:border-white/20'}`}>
                <span className="text-2xl group-hover:scale-125 transition-transform">{style.icon}</span>
                <span className={`text-[10px] font-bold uppercase tracking-tighter ${selectedStyleId === style.id ? 'text-white' : 'text-white/60 group-hover:text-white'}`}>{style.label}</span>
              </button>
            ))}
          </div>
        </div>
        <CustomizationPanel options={project.options} setOptions={(opt) => updateActiveProjectState(p => { p.options = opt; })} />
        <PromptEditor prompt={project.prompt} setPrompt={(p) => updateActiveProjectState(pr => { pr.prompt = p; })} isAutoGenerated={project.isPromptAutoGenerated} onResetPrompt={() => updateActiveProjectState(p => { p.isPromptAutoGenerated = !p.isPromptAutoGenerated; })} translatedPrompt={project.translatedPrompt} isTranslating={project.isTranslating} onUseTranslation={(t) => updateActiveProjectState(p => { p.prompt = t; })} />
        <button onClick={handleGenerate} disabled={project.isLoading || project.uploadingTarget !== null || project.productImages.length === 0} className="w-full bg-[var(--color-accent)] hover:bg-[var(--color-accent-dark)] text-white font-black py-5 rounded-2xl text-lg shadow-xl shadow-[var(--color-accent)]/20 transition-all uppercase tracking-widest disabled:opacity-50">
          {project.isLoading ? 'جاري ابتكار التصميم...' : 'ابتكار التصميم بالذكاء الاصطناعي'}
        </button>
        {project.error && <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-xl text-xs font-bold text-center">{project.error}</div>}
      </div>
      <div className="flex flex-col gap-6 order-2">
        <div className="glass-card rounded-[2.5rem] p-6 min-h-[400px] border border-white/5 shadow-2xl bg-black/40">
          <ResultDisplay imageFile={project.generatedImage} isLoading={project.isLoading} isEditing={project.isEditing} onEdit={handleEdit} />
        </div>
        <HistoryPanel history={project.history} onSelect={(img) => updateActiveProjectState(p => { p.generatedImage = img; })} />
      </div>
    </main>
  );
};

export default CreatorStudio;
